namespace: ecomm
entity: stk_purchase_order_item
description: 采购单商品明细
primaryKeys:
  - id
fields:
  - name: id
    type: LONG
    indexed: true
    description: 主键
  - name: purchase_id
    type: LONG
    index: numeric
    relatedEntity: stk_purchase_order
    description: 外键关联 stk_purchase_order
  - name: sku_id
    type: LONG
    index: numeric
    relatedEntity: prd_sku
    description: 外键关联 prd_sku
  - name: created_at
    type: LONG
    index: numeric
    description: 毫秒时间戳
  - name: purchase_qty
    type: INT
    index: numeric
    description: 采购数量
  - name: inbound_qty
    type: INT
    index: numeric
    description: 入库数量
  - name: cost_price
    type: DOUBLE
    index: numeric
    description: 成本价格（元）
  - name: amount
    type: DOUBLE
    index: numeric
    description: 金额（元）
