namespace: ecomm
entity: prd_product_image
description: 商品图片集
primaryKeys:
  - id
fields:
  - name: id
    type: LONG
    indexed: true
    description: 主键
  - name: product_id
    type: LONG
    index: numeric
    relatedEntity: prd_product
    description: 外键关联 prd_product
  - name: image_type
    type: INT
    index: numeric
    description: 图片类型
    values: 1=主图; 2=轮播图; 3=详情图; 4=白底图
  - name: created_at
    type: LONG
    index: numeric
    description: 毫秒时间戳
  - name: image_url
    type: STRING
    index: tag
    description: 图片地址
  - name: sort
    type: INT
    index: numeric
    description: 排序值（小在前）
  - name: file_size
    type: INT
    index: numeric
    description: 文件尺寸
  - name: width
    type: INT
    index: numeric
    description: 宽度（cm）
  - name: height
    type: INT
    index: numeric
    description: 高度（cm）
