namespace: ecomm
entity: ord_order_confirm
description: 订单确认收货记录
primaryKeys:
  - id
fields:
  - name: id
    type: LONG
    indexed: true
    description: 主键
  - name: order_id
    type: LONG
    index: numeric
    relatedEntity: ord_order
    description: 外键关联 ord_order
  - name: confirm_type
    type: INT
    index: numeric
    description: 确认类型
    values: 1=用户手动; 2=系统自动; 3=客服代确认
  - name: operator_id
    type: LONG
    index: numeric
    description: 操作人ID
  - name: expire_days
    type: INT
    index: numeric
    description: 过期天数
  - name: confirm_at
    type: LONG
    index: numeric
    description: 确认时间（毫秒时间戳）
