namespace: ecomm
entity: mch_shop_role
description: 店铺内部角色定义
primaryKeys:
  - id
fields:
  - name: id
    type: LONG
    indexed: true
    description: 主键
  - name: shop_id
    type: LONG
    index: numeric
    relatedEntity: mch_shop
    description: 外键关联 mch_shop
  - name: role_code
    type: STRING
    index: tag
    description: 角色编码
  - name: created_at
    type: LONG
    index: numeric
    description: 毫秒时间戳
  - name: role_name
    type: STRING
    index: text
    description: 角色名称
  - name: perm_codes
    type: STRING
    index: tag
    description: 权限点编码列表
  - name: remark
    type: STRING
    index: text
    description: 备注
