namespace: ecomm
entity: ops_message_user
description: 消息的用户触达明细（含已读状态）
primaryKeys:
  - id
fields:
  - name: id
    type: LONG
    indexed: true
    description: 主键
  - name: message_id
    type: LONG
    index: numeric
    relatedEntity: ops_message
    description: 外键关联 ops_message
  - name: member_id
    type: LONG
    index: numeric
    relatedEntity: usr_member
    description: 外键关联 usr_member
  - name: is_read
    type: INT
    index: numeric
    description: 是否阅读
    values: 0=否; 1=是
  - name: created_at
    type: LONG
    index: numeric
    description: 毫秒时间戳
  - name: title
    type: STRING
    index: text
    description: 标题
  - name: content
    type: STRING
    index: text
    description: 内容
  - name: biz_type
    type: INT
    index: numeric
    description: 业务类型
    values: 1=订单; 2=物流; 3=活动; 4=账户; 5=系统
  - name: biz_no
    type: STRING
    index: tag
    description: 业务单号
  - name: read_at
    type: LONG
    index: numeric
    description: 阅读时间（毫秒时间戳）
