namespace: ecomm
entity: base_admin_user_role
description: 后台管理员与角色关联表
primaryKeys:
  - id
fields:
  - name: id
    type: LONG
    indexed: true
    description: 主键
  - name: admin_id
    type: LONG
    index: numeric
    relatedEntity: base_admin_user
    description: 外键关联 base_admin_user
  - name: role_id
    type: LONG
    index: numeric
    relatedEntity: base_admin_role
    description: 外键关联 base_admin_role
  - name: created_at
    type: LONG
    index: numeric
    description: 毫秒时间戳
