namespace: ecomm
entity: prd_attribute
description: 商品属性键定义（规格/参数）
primaryKeys:
  - id
fields:
  - name: id
    type: LONG
    indexed: true
    description: 主键
  - name: category_id
    type: LONG
    index: numeric
    relatedEntity: prd_category
    description: 外键关联 prd_category
  - name: created_at
    type: LONG
    index: numeric
    description: 毫秒时间戳
  - name: attr_name
    type: STRING
    index: text
    description: 属性名
  - name: attr_type
    type: INT
    index: numeric
    description: 属性类型
    values: 1=销售属性(规格); 2=参数属性
  - name: input_type
    type: INT
    index: numeric
    description: 录入类型
    values: 1=下拉选择; 2=手动输入
  - name: sort
    type: INT
    index: numeric
    description: 排序值（小在前）
  - name: status
    type: INT
    index: numeric
    description: 状态码
    values: 0=停用; 1=启用
  - name: updated_at
    type: LONG
    index: numeric
    description: 更新时间（毫秒时间戳）
