namespace: ecomm
entity: mkt_groupbuy_member
description: 拼团参与会员记录
primaryKeys:
  - id
fields:
  - name: id
    type: LONG
    indexed: true
    description: 主键
  - name: team_id
    type: LONG
    index: numeric
    relatedEntity: mkt_groupbuy_team
    description: 外键关联 mkt_groupbuy_team
  - name: member_id
    type: LONG
    index: numeric
    relatedEntity: usr_member
    description: 外键关联 usr_member
  - name: order_id
    type: LONG
    index: numeric
    relatedEntity: ord_order
    description: 外键关联 ord_order
  - name: is_leader
    type: INT
    index: numeric
    description: 是否负责人
    values: 0=否; 1=是
  - name: join_status
    type: INT
    index: numeric
    description: 加入状态
    values: 0=参团中; 1=成功; 2=已退款
  - name: join_at
    type: LONG
    index: numeric
    description: 加入时间（毫秒时间戳）
