namespace: ecomm
entity: base_admin_user
description: 后台管理员账号
primaryKeys:
  - id
fields:
  - name: id
    type: LONG
    indexed: true
    description: 主键
  - name: username
    type: STRING
    index: tag
    description: 登录用户名
  - name: mobile
    type: STRING
    index: tag
    description: 手机号
  - name: shop_id
    type: LONG
    index: numeric
    relatedEntity: mch_shop
    description: 外键关联 mch_shop
  - name: created_at
    type: LONG
    index: numeric
    description: 毫秒时间戳
  - name: password_hash
    type: STRING
    index: tag
    description: 密码哈希
  - name: real_name
    type: STRING
    index: text
    description: 真实姓名
  - name: email
    type: STRING
    index: tag
    description: 邮箱
  - name: avatar
    type: STRING
    index: tag
    description: 头像地址
  - name: user_type
    type: INT
    index: numeric
    description: 用户类型
    values: 1=超级管理员; 2=平台运营; 3=商家管理员
  - name: status
    type: INT
    index: numeric
    description: 状态码
    values: 0=禁用; 1=启用
  - name: last_login_at
    type: LONG
    index: numeric
    description: 最近登录时间（毫秒时间戳）
  - name: last_login_ip
    type: STRING
    index: tag
    description: 最近登录IP 地址
  - name: login_count
    type: INT
    index: numeric
    description: 登录次数
  - name: updated_at
    type: LONG
    index: numeric
    description: 更新时间（毫秒时间戳）
