namespace: ecomm
entity: prd_product_detail
description: 商品详情富文本
primaryKeys:
  - id
fields:
  - name: id
    type: LONG
    indexed: true
    description: 主键
  - name: product_id
    type: LONG
    index: numeric
    relatedEntity: prd_product
    description: 外键关联 prd_product
  - name: created_at
    type: LONG
    index: numeric
    description: 毫秒时间戳
  - name: packing_list
    type: STRING
    index: tag
    description: 打包列表
  - name: after_sale_desc
    type: STRING
    index: text
    description: 售后描述
  - name: updated_at
    type: LONG
    index: numeric
    description: 更新时间（毫秒时间戳）
